# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site.
#
title: 汽车资讯小站
email: 
description: 最新汽车资讯、车型评测、行业动态
baseurl: ""
url: "https://car-blog-test.netlify.app"

# Social
github_username: elo-bo-lang

# Build settings
markdown: kramdown
remote_theme: academicpages/academicpages.github.io

# 分页
paginate: 5
paginate_path: /blog/page:num/

# 语言
locale: zh-CN
